# -*- coding: utf-8 -*-
"""rf_algo_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SqRx87gQ0Kg0MEo8OPauCVF2NfiwInF_
"""

import pandas as pd

df=pd.read_csv('car.csv')

#df.head()

#datasett=pd.get_dummies(df,drop_first=True)
#datasett

#print(datasett['Selling_Price'].unique())
#print(datasett['Present_Price'].unique())
#print(datasett['Kms_Driven'].unique())
#print(datasett['Year'].unique())

print(df['Seller_Type'].unique())
print(df['Fuel_Type'].unique())
print(df['Transmission'].unique())
print(df['Owner'].unique())

df.describe()

final_dataset=df[['Year','Selling_Price','Present_Price','Kms_Driven','Fuel_Type','Seller_Type','Transmission','Owner']]

final_dataset.head()

final_dataset['Current Year']=2020

final_dataset.head()

final_dataset['no_year']=final_dataset['Current Year']- final_dataset['Year']

final_dataset.head()

final_dataset.drop(['Year'],axis=1,inplace=True)

final_dataset.head()

final_dataset=pd.get_dummies(final_dataset,drop_first=True)

final_dataset.head()

final_dataset=final_dataset.drop(['Current Year'],axis=1)

final_dataset.head()

final_dataset.corr()

import seaborn as sns

sns.jointplot(x='Selling_Price',y='Year',data=df,color='red',kind='kde');

sns.pointplot(y="Selling_Price", x="Kms_Driven", data=df)

sns.boxplot(x="Year", y="Kms_Driven", data=df)

plt.figure(figsize=(10,6))
df['Owner'].hist(alpha=0.5,color='blue',label='Front camera')
df['Kms_Driven'].hist(alpha=0.5,color='red',label='Primary camera')
plt.legend()
plt.xlabel('MegaPixels')

ax = sns.boxplot(x=df.Present_Price, orient='v')

ax = sns.pairplot(df, y_vars='Selling_Price', x_vars=['Present_Price'], kind='reg', height=5)
ax.fig.suptitle('Selling_Price and Present_Price', fontsize=20, y=1.05)
ax

sns.pairplot(final_dataset,kind="reg")

ax = sns.pairplot(df, y_vars='Selling_Price', x_vars=['Kms_Driven'], kind='reg', height=5)
ax.fig.suptitle('Selling_Price and Kms_Driven', fontsize=20, y=1.05)
ax

import matplotlib.pyplot as plt
import seaborn as sns
#get correlations of each features in dataset
corrmat = df.corr()
top_corr_features = corrmat.index
plt.figure(figsize=(20,20))
#plot heat map
g=sns.heatmap(df[top_corr_features].corr(),annot=True,cmap="BuPu")

X=final_dataset.iloc[:,1:]
y=final_dataset.iloc[:,0]

X['Owner'].unique()

X.head()

y.head()

from sklearn.ensemble import ExtraTreesRegressor
import matplotlib.pyplot as plt
model = ExtraTreesRegressor()
model.fit(X,y)

print(model.feature_importances_)

feat_importances = pd.Series(model.feature_importances_, index=X.columns)
feat_importances.nlargest(5).plot(kind='barh')
plt.show()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

from sklearn.ensemble import RandomForestRegressor

regressor=RandomForestRegressor()

import numpy as np
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
print(n_estimators)

from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

rf = RandomForestRegressor()

rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid,scoring='neg_mean_squared_error', n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

rf_random.fit(X_train,y_train)

rf_random.best_params_

rf_random.best_score_

predictions=rf_random.predict(X_test)

sns.distplot(y_test-predictions)

plt.scatter(y_test,predictions)

from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

import pickle
# open a file, where you ant to store the data
filee = open('random_forest_regression_model.pkl', 'wb')

# dump information to that file
pickle.dump(rf_random, filee)